#!/usr/bin/env sh
set -eu

INPUT_PATH=""
OUTPUT_PATH=""

usage() {
  cat <<'EOF'
Usage: render-progress-ledger.sh --input <docs/tasks/.../super-plan.json> [--output <docs/tasks/.../progress-ledger.md>]
EOF
  exit 1
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --input)
      INPUT_PATH="$2"
      shift 2
      ;;
    --output)
      OUTPUT_PATH="$2"
      shift 2
      ;;
    *)
      usage
      ;;
  esac
done

if [ -z "$INPUT_PATH" ]; then
  usage
fi

if [ -z "$OUTPUT_PATH" ]; then
  OUTPUT_PATH="$(dirname "$INPUT_PATH")/progress-ledger.md"
fi

mkdir -p "$(dirname "$OUTPUT_PATH")"

python3 - "$INPUT_PATH" "$OUTPUT_PATH" <<'PY'
import json
import sys
from datetime import datetime, timezone

input_path, output_path = sys.argv[1:]

with open(input_path, "r", encoding="utf-8") as fh:
    payload = json.load(fh)

status_map = {
    "pending": ("⏳ pending", "—"),
    "in_progress": ("🔄 in progress", "implementer running"),
    "ready_for_review": ("🔎 ready for review", "awaiting review"),
    "needs_fix": ("🔁 needs-fix", "critical/important findings open"),
    "blocked": ("❌ blocked", "needs context or plan change"),
    "completed": ("✅ complete", "clean"),
}

generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
lines = [
    "# Progress Ledger",
    "",
    f"- Generated from `{input_path}`",
    f"- Last generated: `{generated_at}`",
    "- Do not edit this file by hand. Re-run the super-plan script so the ledger stays in sync.",
    "",
    "| Task | Status | Commits | Report File | Review |",
    "| ---- | ------ | ------- | ----------- | ------ |",
]

tasks = payload.get("tasks", [])
for task in tasks:
    task_id = task.get("id", "—")
    status_label, review_label = status_map.get(task.get("status"), (task.get("status", "unknown"), "—"))
    report_file = task.get("reportFile") or "—"
    lines.append(f"| {task_id} | {status_label} | — | {report_file} | {review_label} |")

if not tasks:
    lines.append("| — | ⏳ pending | — | — | no tasks defined yet |")

lines.extend(
    [
        "",
        "## Notes",
        "",
        f"- Plan id: `{payload.get('planId', '')}`",
        f"- Plan status: `{payload.get('status', '')}`",
        f"- Execution mode: `{payload.get('executionMode', '')}`",
        f"- Review cadence: `{payload.get('reviewCadence', '')}`",
        f"- Feature branch: `{payload.get('branchStrategy', {}).get('featureBranch', '')}`",
    ]
)

with open(output_path, "w", encoding="utf-8") as fh:
    fh.write("\n".join(lines))
    fh.write("\n")
PY

printf '%s\n' "$OUTPUT_PATH"
